name: Test

on:
  workflow_dispatch:
    branches:
      - main

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.20.2

    - name: Install dependecies
      run: yarn

    - name: Check tests
      run: yarn test

    - name: Check liting
      run: yarn lint

    - name: Coveralls
      uses: coverallsapp/github-action@v2
